"""create auth tables

Revision ID: 400c87388bd6
Revises:
Create Date: 2026-06-12 09:55:04.949337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid

# revision identifiers, used by Alembic.
revision: str = "400c87388bd6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    # 1. Define the structural schema of your existing 'roles' table so Alembic understands it
    meta = sa.MetaData()
    roles_table = sa.Table(
        "roles",
        meta,
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("name", sa.String(), unique=True, nullable=False),
    )
    # 2. Seed 'Customer' and 'Admin' roles immediately
    op.bulk_insert(
        roles_table,
        [
            {"id": str(uuid.uuid4()), "name": "Customer"},  # ← Wrapped in str()
            {"id": str(uuid.uuid4()), "name": "Admin"},  # ← Wrapped in str()
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    # ### end Alembic commands ###
