from decimal import Decimal

CATEGORY_SEEDS = [
    {
        "name": "Laptops",
        "slug": "laptops",
        "description": "Portable computers for work, study, and gaming.",
    },
    {
        "name": "Smartphones",
        "slug": "smartphones",
        "description": "Flagship and mid-range mobile devices.",
    },
    {
        "name": "Audio",
        "slug": "audio",
        "description": "Headphones, earbuds, speakers, and microphones.",
    },
    {
        "name": "Wearables",
        "slug": "wearables",
        "description": "Smart watches, fitness trackers, and wellness wearables.",
    },
    {
        "name": "Accessories",
        "slug": "accessories",
        "description": "Chargers, cables, keyboards, and daily productivity tools.",
    },
    {
        "name": "Gaming",
        "slug": "gaming",
        "description": "Consoles, controllers, and gaming peripherals.",
    },
    {
        "name": "Home Office",
        "slug": "home-office",
        "description": "Monitors, docks, and office gear for hybrid teams.",
    },
    {
        "name": "Smart Home",
        "slug": "smart-home",
        "description": "Connected devices for automation, lighting, and security.",
    },
]


def _asset_url(asset_name: str) -> str:
    return f"/assets/catalog/{asset_name}.svg"


PRODUCT_SEEDS = [
    {
        "sku": "LAP-ULTRA-14",
        "name": "Apex Ultralight 14",
        "description": "14-inch productivity laptop with all-day battery life.",
        "price": Decimal("1299.00"),
        "stock": 18,
        "category": "Laptops",
        "image_url": _asset_url("laptops"),
        "image_alt": "Apex Ultralight 14 laptop illustration",
    },
    {
        "sku": "LAP-CREATOR-16",
        "name": "Forge Creator 16",
        "description": "High-performance laptop for design and video editing workloads.",
        "price": Decimal("1899.00"),
        "stock": 9,
        "category": "Laptops",
        "image_url": _asset_url("laptops"),
        "image_alt": "Forge Creator 16 laptop illustration",
    },
    {
        "sku": "LAP-STUDENT-13",
        "name": "Nimbus Student 13",
        "description": "Lightweight 13-inch laptop suited for students and travel.",
        "price": Decimal("799.00"),
        "stock": 27,
        "category": "Laptops",
        "image_url": _asset_url("laptops"),
        "image_alt": "Nimbus Student 13 laptop illustration",
    },
    {
        "sku": "PHN-NOVA-X",
        "name": "Nova X Pro",
        "description": "Premium smartphone with pro-grade camera system and OLED display.",
        "price": Decimal("999.00"),
        "stock": 21,
        "category": "Smartphones",
        "image_url": _asset_url("smartphones"),
        "image_alt": "Nova X Pro smartphone illustration",
    },
    {
        "sku": "PHN-NOVA-LITE",
        "name": "Nova Lite 5G",
        "description": "Balanced 5G smartphone with strong battery life and stereo audio.",
        "price": Decimal("549.00"),
        "stock": 34,
        "category": "Smartphones",
        "image_url": _asset_url("smartphones"),
        "image_alt": "Nova Lite 5G smartphone illustration",
    },
    {
        "sku": "PHN-TERRA-MAX",
        "name": "Terra Max",
        "description": "Large-format smartphone focused on media and productivity.",
        "price": Decimal("849.00"),
        "stock": 14,
        "category": "Smartphones",
        "image_url": _asset_url("smartphones"),
        "image_alt": "Terra Max smartphone illustration",
    },
    {
        "sku": "AUD-STUDIO-ANC",
        "name": "Studio ANC Headphones",
        "description": "Wireless over-ear headphones with adaptive noise cancellation.",
        "price": Decimal("299.00"),
        "stock": 16,
        "category": "Audio",
        "image_url": _asset_url("audio"),
        "image_alt": "Studio ANC headphones illustration",
    },
    {
        "sku": "AUD-FIT-BUDS",
        "name": "FitBuds Sport",
        "description": "Sweat-resistant earbuds with secure fit for workouts.",
        "price": Decimal("119.00"),
        "stock": 42,
        "category": "Audio",
        "image_url": _asset_url("audio"),
        "image_alt": "FitBuds Sport earbuds illustration",
    },
    {
        "sku": "AUD-WAVE-SPKR",
        "name": "Wave Mini Speaker",
        "description": "Compact Bluetooth speaker with room-filling sound.",
        "price": Decimal("89.00"),
        "stock": 25,
        "category": "Audio",
        "image_url": _asset_url("audio"),
        "image_alt": "Wave Mini Speaker illustration",
    },
    {
        "sku": "WRB-PULSE-2",
        "name": "Pulse Watch 2",
        "description": "Smart watch with fitness, sleep, and notification tracking.",
        "price": Decimal("249.00"),
        "stock": 19,
        "category": "Wearables",
        "image_url": _asset_url("wearables"),
        "image_alt": "Pulse Watch 2 wearable illustration",
    },
    {
        "sku": "WRB-TRACK-FLEX",
        "name": "TrackFlex Band",
        "description": "Slim fitness tracker with heart-rate and recovery insights.",
        "price": Decimal("79.00"),
        "stock": 48,
        "category": "Wearables",
        "image_url": _asset_url("wearables"),
        "image_alt": "TrackFlex Band illustration",
    },
    {
        "sku": "ACC-DOCK-USB4",
        "name": "USB4 Work Dock",
        "description": "Multi-port dock for laptops with display and network expansion.",
        "price": Decimal("179.00"),
        "stock": 12,
        "category": "Accessories",
        "image_url": _asset_url("accessories"),
        "image_alt": "USB4 Work Dock illustration",
    },
    {
        "sku": "ACC-MECH-KEY",
        "name": "Mechanical Keyboard K87",
        "description": "Tactile compact keyboard with hot-swappable switches.",
        "price": Decimal("139.00"),
        "stock": 17,
        "category": "Accessories",
        "image_url": _asset_url("accessories"),
        "image_alt": "Mechanical Keyboard K87 illustration",
    },
    {
        "sku": "ACC-GA-CHARGE",
        "name": "GaN Fast Charger 100W",
        "description": "Compact charger supporting laptops, tablets, and phones.",
        "price": Decimal("69.00"),
        "stock": 58,
        "category": "Accessories",
        "image_url": _asset_url("accessories"),
        "image_alt": "GaN Fast Charger 100W illustration",
    },
    {
        "sku": "GME-CONTROL-PRO",
        "name": "Control Pro Wireless",
        "description": "Low-latency wireless controller for console and PC gaming.",
        "price": Decimal("74.00"),
        "stock": 23,
        "category": "Gaming",
        "image_url": _asset_url("gaming"),
        "image_alt": "Control Pro Wireless controller illustration",
    },
    {
        "sku": "GME-HEADSET-7",
        "name": "Arena 7 Headset",
        "description": "Immersive gaming headset with virtual surround audio.",
        "price": Decimal("129.00"),
        "stock": 15,
        "category": "Gaming",
        "image_url": _asset_url("gaming"),
        "image_alt": "Arena 7 gaming headset illustration",
    },
    {
        "sku": "GME-STREAM-CAM",
        "name": "Streamer Cam 4K",
        "description": "4K webcam optimized for streaming and remote collaboration.",
        "price": Decimal("159.00"),
        "stock": 11,
        "category": "Gaming",
        "image_url": _asset_url("gaming"),
        "image_alt": "Streamer Cam 4K illustration",
    },
    {
        "sku": "OFF-MONITOR-27",
        "name": "Clarity Monitor 27",
        "description": "27-inch QHD monitor with USB-C connectivity for desks.",
        "price": Decimal("329.00"),
        "stock": 13,
        "category": "Home Office",
        "image_url": _asset_url("home-office"),
        "image_alt": "Clarity Monitor 27 illustration",
    },
    {
        "sku": "OFF-STAND-DUAL",
        "name": "Dual Monitor Arm",
        "description": "Adjustable arm mount to optimize desk ergonomics.",
        "price": Decimal("149.00"),
        "stock": 20,
        "category": "Home Office",
        "image_url": _asset_url("home-office"),
        "image_alt": "Dual Monitor Arm illustration",
    },
    {
        "sku": "OFF-MIC-VOICE",
        "name": "VoiceFocus USB Mic",
        "description": "Desktop USB microphone for conferencing and podcast recording.",
        "price": Decimal("109.00"),
        "stock": 26,
        "category": "Home Office",
        "image_url": _asset_url("home-office"),
        "image_alt": "VoiceFocus USB Mic illustration",
    },
    {
        "sku": "SMH-HUB-CENTER",
        "name": "HomeHub Center",
        "description": "Smart home hub that coordinates lighting, climate, and sensors.",
        "price": Decimal("199.00"),
        "stock": 8,
        "category": "Smart Home",
        "image_url": _asset_url("smart-home"),
        "image_alt": "HomeHub Center illustration",
    },
    {
        "sku": "SMH-CAM-GUARD",
        "name": "Guard Indoor Cam",
        "description": "Indoor security camera with motion zones and cloud playback.",
        "price": Decimal("129.00"),
        "stock": 24,
        "category": "Smart Home",
        "image_url": _asset_url("smart-home"),
        "image_alt": "Guard Indoor Cam illustration",
    },
    {
        "sku": "SMH-BULB-COLOR",
        "name": "ColorGlow Bulb Pack",
        "description": "Energy-efficient smart bulbs with scenes and automation.",
        "price": Decimal("59.00"),
        "stock": 37,
        "category": "Smart Home",
        "image_url": _asset_url("smart-home"),
        "image_alt": "ColorGlow Bulb Pack illustration",
    },
    {
        "sku": "ACC-CABLE-THUNDER",
        "name": "ThunderLink Cable",
        "description": "High-bandwidth braided cable for docks, displays, and storage.",
        "price": Decimal("39.00"),
        "stock": 63,
        "category": "Accessories",
        "image_url": _asset_url("accessories"),
        "image_alt": "ThunderLink Cable illustration",
    },
]


ADMIN_USER_SEED = {
    "email": "admin@enterprise-shop.local",
    "password": "Admin@12345",
    "role_name": "Admin",
}


CUSTOMER_USER_SEED = {
    "email": "customer@enterprise-shop.local",
    "password": "Customer@12345",
    "role_name": "Customer",
}
