"""
Master product catalog — 30 products across the 5 categories.

`category` here is the plain string stored on Product.category (see the
note in seed_data/categories.py about the missing category_id FK).
`image_url` is populated at seed time by generate_placeholder_images.py.
"""

PRODUCTS = [
    # -- Electronics --------------------------------------------------
    {"sku": "ELEC-001", "name": "Pulse 6 Smartphone", "category": "Electronics",
     "description": "6.5-inch OLED smartphone with triple-lens camera, 128GB storage, and all-day battery life.",
     "price": "699.99", "stock_quantity": 42},
    {"sku": "ELEC-002", "name": "AeroTab 11 Tablet", "category": "Electronics",
     "description": "11-inch tablet with stylus support, ideal for note-taking, sketching, and media streaming.",
     "price": "449.00", "stock_quantity": 30},
    {"sku": "ELEC-003", "name": "OrbitCam Security Camera", "category": "Electronics",
     "description": "1080p Wi-Fi security camera with night vision, motion alerts, and two-way audio.",
     "price": "59.99", "stock_quantity": 85},
    {"sku": "ELEC-004", "name": "FlexBand Fitness Tracker", "category": "Electronics",
     "description": "Lightweight fitness band tracking heart rate, sleep, and steps with a 10-day battery.",
     "price": "39.50", "stock_quantity": 120},
    {"sku": "ELEC-005", "name": "VoltCharge 65W GaN Charger", "category": "Electronics",
     "description": "Compact 65W GaN fast charger with dual USB-C ports for phones and laptops.",
     "price": "34.99", "stock_quantity": 200},
    {"sku": "ELEC-006", "name": "LumaStream 4K Streaming Stick", "category": "Electronics",
     "description": "4K HDR streaming stick with voice remote and support for all major apps.",
     "price": "49.99", "stock_quantity": 75},

    # -- Computers ------------------------------------------------------
    {"sku": "COMP-001", "name": "Nimbus 14 Ultrabook", "category": "Computers",
     "description": "14-inch ultrabook with a 12-core CPU, 16GB RAM, and 512GB NVMe SSD.",
     "price": "1199.00", "stock_quantity": 25},
    {"sku": "COMP-002", "name": "ForgeStation Desktop Tower", "category": "Computers",
     "description": "Mid-tower desktop with discrete graphics, tuned for creative and dev workloads.",
     "price": "1599.00", "stock_quantity": 15},
    {"sku": "COMP-003", "name": "ClearView 27\" 4K Monitor", "category": "Computers",
     "description": "27-inch 4K IPS monitor with 99% sRGB coverage and a slim-bezel design.",
     "price": "379.99", "stock_quantity": 34},
    {"sku": "COMP-004", "name": "TypeCraft Mechanical Keyboard", "category": "Computers",
     "description": "Hot-swappable mechanical keyboard with tactile switches and per-key RGB.",
     "price": "119.00", "stock_quantity": 60},
    {"sku": "COMP-005", "name": "GlideMax Wireless Mouse", "category": "Computers",
     "description": "Ergonomic wireless mouse with a 4000 DPI sensor and silent clicks.",
     "price": "29.99", "stock_quantity": 150},
    {"sku": "COMP-006", "name": "DockPro 12-in-1 USB-C Hub", "category": "Computers",
     "description": "12-in-1 USB-C docking hub with HDMI, Ethernet, SD card, and 100W pass-through.",
     "price": "64.99", "stock_quantity": 70},
    {"sku": "COMP-007", "name": "VaultDrive 2TB External SSD", "category": "Computers",
     "description": "Pocket-sized 2TB external SSD with USB 3.2 speeds up to 1050MB/s.",
     "price": "159.99", "stock_quantity": 55},

    # -- Footwear ---------------------------------------------------
    {"sku": "SHOE-001", "name": "TrailBlaze Hiking Boots", "category": "Footwear",
     "description": "Waterproof hiking boots with reinforced ankle support and a grippy lug sole.",
     "price": "129.99", "stock_quantity": 38},
    {"sku": "SHOE-002", "name": "SprintCore Running Shoes", "category": "Footwear",
     "description": "Lightweight running shoes with responsive foam cushioning for daily mileage.",
     "price": "94.99", "stock_quantity": 90},
    {"sku": "SHOE-003", "name": "UrbanFlex Casual Sneakers", "category": "Footwear",
     "description": "Everyday sneakers with a knit upper and a cushioned, flexible sole.",
     "price": "69.99", "stock_quantity": 110},
    {"sku": "SHOE-004", "name": "CourtSide Basketball Shoes", "category": "Footwear",
     "description": "High-top basketball shoes with mid-cut support and impact-absorbing midsoles.",
     "price": "114.99", "stock_quantity": 48},
    {"sku": "SHOE-005", "name": "RainGuard Ankle Boots", "category": "Footwear",
     "description": "Sealed-seam ankle boots built to keep feet dry in wet, cold weather.",
     "price": "84.99", "stock_quantity": 33},
    {"sku": "SHOE-006", "name": "GlideWalk Slip-On Loafers", "category": "Footwear",
     "description": "Slip-on loafers with a memory-foam footbed for all-day office comfort.",
     "price": "59.99", "stock_quantity": 65},

    # -- Home -----------------------------------------------------------
    {"sku": "HOME-001", "name": "BrewMaster Drip Coffee Maker", "category": "Home",
     "description": "12-cup programmable drip coffee maker with a reusable gold-tone filter.",
     "price": "54.99", "stock_quantity": 52},
    {"sku": "HOME-002", "name": "AeroFlow Tower Fan", "category": "Home",
     "description": "Quiet oscillating tower fan with 3 speeds and a remote control.",
     "price": "74.99", "stock_quantity": 40},
    {"sku": "HOME-003", "name": "PureAir HEPA Purifier", "category": "Home",
     "description": "True HEPA air purifier covering rooms up to 350 sq ft, with a quiet-night mode.",
     "price": "129.00", "stock_quantity": 27},
    {"sku": "HOME-004", "name": "GlowNest LED Desk Lamp", "category": "Home",
     "description": "Dimmable LED desk lamp with adjustable color temperature and USB charging port.",
     "price": "32.99", "stock_quantity": 95},
    {"sku": "HOME-005", "name": "ChopEase 8-Piece Knife Set", "category": "Home",
     "description": "8-piece stainless steel knife set with a wooden block and built-in sharpener.",
     "price": "89.99", "stock_quantity": 36},
    {"sku": "HOME-006", "name": "SoftRest Memory Foam Pillow", "category": "Home",
     "description": "Contoured memory foam pillow designed to relieve neck and shoulder tension.",
     "price": "39.99", "stock_quantity": 80},

    # -- Audio ----------------------------------------------------------
    {"sku": "AUD-001", "name": "EchoBeam Bluetooth Speaker", "category": "Audio",
     "description": "Portable Bluetooth speaker with 360-degree sound and 20 hours of playback.",
     "price": "79.99", "stock_quantity": 58},
    {"sku": "AUD-002", "name": "SilentWave ANC Headphones", "category": "Audio",
     "description": "Over-ear active noise-cancelling headphones with 30-hour battery life.",
     "price": "199.99", "stock_quantity": 44},
    {"sku": "AUD-003", "name": "PulsePods True Wireless Earbuds", "category": "Audio",
     "description": "True wireless earbuds with a compact charging case and IPX4 sweat resistance.",
     "price": "99.99", "stock_quantity": 130},
    {"sku": "AUD-004", "name": "VinylCraft Turntable", "category": "Audio",
     "description": "Belt-driven turntable with a built-in preamp and Bluetooth output.",
     "price": "179.00", "stock_quantity": 20},
    {"sku": "AUD-005", "name": "StageMic USB Condenser Microphone", "category": "Audio",
     "description": "Cardioid USB condenser microphone for podcasting, streaming, and voiceover work.",
     "price": "89.99", "stock_quantity": 50},
]
